struct {
    float4x4 viewMatrix;
    float4x4 projectionMatrix;
} CameraBuffer : BUFFER[0];

uniform struct {
    float4x4 worldMatrix;
} ModelBuffer : BUFFER[1];

void main(float3 aPosition, float4 aColor,
	out float4 position : POSITION,
	out float4 color : COLOR)
{
    position = mul(float4(aPosition, 1.0f), ModelBuffer.worldMatrix);
    position = mul(position, CameraBuffer.viewMatrix);
    position = mul(position, CameraBuffer.projectionMatrix);

    color = aColor;
}