#ifndef AES_MACRO_HELPERS_HPP
#define AES_MACRO_HELPERS_HPP

#define AES_CONCAT_DETAIL(X, Y) X##Y
#define AES_CONCAT(X, Y) AES_CONCAT_DETAIL(X, Y)
#define AES_STRINGIFY_DETAIL(X) #X
#define AES_STRINGIFY(X) AES_STRINGIFY_DETAIL(X)

#endif