#ifndef WOB_MACRO_HELPERS_HPP
#define WOB_MACRO_HELPERS_HPP

#define WOB_CONCAT_DETAIL(X, Y) X##Y
#define WOB_CONCAT(X, Y) WOB_CONCAT_DETAIL(X, Y)
#define WOB_STRINGIFY_DETAIL(X) #X
#define WOB_STRINGIFY(X) WOB_STRINGIFY_DETAIL(X)

#endif